"use client"

import { useState } from "react"
import { Card } from "../../components/ui/card"
import { Button } from "../../components/ui/button"
import { Badge } from "../../components/ui/badge"
import { Input } from "../../components/ui/input"
import { FileText, Download, Search, Eye, Calendar, Brain, X } from "lucide-react"
import { mockPatients } from "@/lib/mock-data"
import { PageWrapper } from "@/components/page-wrapper"
import { AnimatedButtonWrapper } from "@/components/animated-button-wrapper"

interface PDFReport {
  id: string
  patientId: string
  patientName: string
  generatedDate: string
  type: "Medical Summary" | "Visit Report" | "Health Analysis"
  size: string
  status: "Generated" | "Processing"
}

export default function ReportsPage() {
  const [searchQuery, setSearchQuery] = useState("")
  const [viewingReport, setViewingReport] = useState<PDFReport | null>(null)

  // Mock PDF reports generated by chatbot
  const mockReports: PDFReport[] = mockPatients.map((patient, index) => ({
    id: `report-${patient.id}`,
    patientId: patient.id,
    patientName: `${patient.first_name} ${patient.last_name}`,
    generatedDate: new Date(Date.now() - index * 86400000).toISOString(),
    type: index % 3 === 0 ? "Medical Summary" : index % 3 === 1 ? "Visit Report" : "Health Analysis",
    size: `${(Math.random() * 500 + 100).toFixed(0)} KB`,
    status: "Generated" as const,
  }))

  const filteredReports = mockReports.filter((report) =>
    report.patientName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    report.type.toLowerCase().includes(searchQuery.toLowerCase())
  )

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    })
  }

  // Generate PDF content as text (for demo purposes)
  const generatePDFContent = (report: PDFReport): string => {
    return `Patient Medical Report
Generated by AI Chatbot

Patient Information:
Name: ${report.patientName}
Report Type: ${report.type}
Generated Date: ${formatDate(report.generatedDate)}
Status: ${report.status}

Report Summary:
This is a comprehensive medical report generated by our AI-powered chatbot system.
The report contains detailed analysis of patient health records, visit history, and medical summaries.

Key Findings:
- Patient records have been reviewed and analyzed
- Medical history has been compiled
- Recommendations have been generated based on AI analysis

This report was automatically generated by the healthcare AI system and contains
sensitive medical information. Please handle with confidentiality.

---
Report ID: ${report.id}
Generated: ${new Date(report.generatedDate).toLocaleString()}
`
  }

  // Create downloadable PDF blob
  const createPDFBlob = (content: string): Blob => {
    // Create a simple text-based PDF representation
    // In a real app, you'd use a library like jsPDF or pdfkit
    const pdfContent = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj
2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj
3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 5 0 R
>>
>>
>>
endobj
4 0 obj
<<
/Length ${content.length}
>>
stream
BT
/F1 12 Tf
100 700 Td
(${content.replace(/[()\\]/g, '\\$&')}) Tj
ET
endstream
endobj
5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000300 00000 n 
0000000500 00000 n 
trailer
<<
/Size 6
/Root 1 0 R
>>
startxref
600
%%EOF`

    return new Blob([pdfContent], { type: 'application/pdf' })
  }

  const handleViewPDF = (reportId: string) => {
    const report = mockReports.find(r => r.id === reportId)
    if (report) {
      setViewingReport(report)
    }
  }

  const handleDownloadPDF = (reportId: string) => {
    const report = mockReports.find(r => r.id === reportId)
    if (!report) return

    const content = generatePDFContent(report)
    const blob = createPDFBlob(content)
    
    // Create download link
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `${report.patientName.replace(/\s+/g, '_')}_${report.type.replace(/\s+/g, '_')}_${report.id}.pdf`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <PageWrapper title="Patient Reports" description="PDF reports generated by AI chatbot">
    <div className="space-y-6">
      {/* Header Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="p-4 bg-gradient-to-br from-zinc-800/95 to-zinc-900/95 backdrop-blur-xl rounded-3xl border border-orange-500/40 shadow-2xl shadow-orange-500/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-3xl bg-gradient-to-br from-orange-500/20 to-orange-600/10 flex items-center justify-center border border-orange-500/30 shadow-md">
              <FileText className="w-5 h-5 text-orange-400" />
            </div>
            <div>
              <p className="text-2xl font-bold text-white">{mockReports.length}</p>
              <p className="text-[10px] text-white/70 uppercase tracking-wider font-semibold">Total Reports</p>
            </div>
          </div>
        </Card>

        <Card className="p-4 bg-gradient-to-br from-zinc-800/95 to-zinc-900/95 backdrop-blur-xl rounded-3xl border border-orange-500/40 shadow-2xl shadow-orange-500/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-3xl bg-gradient-to-br from-orange-500/20 to-orange-600/10 flex items-center justify-center border border-orange-500/30 shadow-md">
              <Brain className="w-5 h-5 text-orange-400" />
            </div>
            <div>
              <p className="text-2xl font-bold text-white">AI Generated</p>
              <p className="text-[10px] text-white/70 uppercase tracking-wider font-semibold">All Reports</p>
            </div>
          </div>
        </Card>

        <Card className="p-4 bg-gradient-to-br from-zinc-800/95 to-zinc-900/95 backdrop-blur-xl rounded-3xl border border-orange-500/40 shadow-2xl shadow-orange-500/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-3xl bg-gradient-to-br from-orange-500/20 to-orange-600/10 flex items-center justify-center border border-orange-500/30 shadow-md">
              <Calendar className="w-5 h-5 text-orange-400" />
            </div>
            <div>
              <p className="text-2xl font-bold text-white">
                {mockReports.filter(r => new Date(r.generatedDate).getMonth() === new Date().getMonth()).length}
              </p>
              <p className="text-[10px] text-white/70 uppercase tracking-wider font-semibold">This Month</p>
            </div>
          </div>
        </Card>
      </div>

      {/* Search Section */}
      <Card className="bg-gradient-to-br from-zinc-800/95 to-zinc-900/95 backdrop-blur-xl rounded-3xl p-6 border border-zinc-700/50 shadow-2xl">
        <div className="relative">
          <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-orange-400 w-5 h-5" />
          <Input 
            placeholder="Search reports by patient name or type..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-12 h-12 rounded-3xl bg-zinc-800/50 border-zinc-700/50 text-white placeholder:text-white/50 focus:border-orange-500/50 focus:ring-2 focus:ring-orange-500/20" 
          />
        </div>
      </Card>

      {/* Reports List */}
      <div className="space-y-4">
        {filteredReports.map((report) => (
          <Card
            key={report.id}
            className="group bg-gradient-to-br from-zinc-800/95 to-zinc-900/95 backdrop-blur-xl rounded-3xl p-6 border border-orange-500/40 shadow-2xl shadow-orange-500/10 hover:shadow-orange-500/20 transition-all duration-300"
          >
            <div className="flex items-start justify-between">
              <div className="flex items-start gap-4 flex-1">
                <div className="w-14 h-14 rounded-3xl bg-gradient-to-br from-orange-500/20 to-orange-600/10 flex items-center justify-center border border-orange-500/30 shadow-md flex-shrink-0">
                  <FileText className="w-7 h-7 text-orange-400" />
                </div>
                
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-3 mb-2">
                    <h3 className="text-lg font-bold text-orange-400">{report.patientName}</h3>
                    <Badge className="rounded-full bg-gradient-to-r from-orange-500/25 to-orange-600/15 text-orange-300 border border-orange-500/40 text-xs px-3 py-0.5">
                      {report.type}
                    </Badge>
                    <Badge className="rounded-full bg-gradient-to-r from-green-500/25 to-green-600/15 text-green-300 border border-green-500/40 text-xs px-3 py-0.5">
                      {report.status}
                    </Badge>
                  </div>
                  
                  <div className="flex items-center gap-4 text-sm text-white/70 mb-3">
                    <div className="flex items-center gap-2">
                      <Calendar className="w-4 h-4 text-orange-400" />
                      <span className="text-xs font-medium">{formatDate(report.generatedDate)}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <FileText className="w-4 h-4 text-orange-400" />
                      <span className="text-xs font-medium">{report.size}</span>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-2 ml-4">
                <Button
                  onClick={() => handleViewPDF(report.id)}
                  className="rounded-full bg-zinc-800/50 border border-orange-500/30 text-orange-400 hover:bg-orange-500/10 hover:border-orange-500/50 transition-all"
                  size="sm"
                >
                  <Eye className="w-4 h-4 mr-2" />
                  View
                </Button>
                <AnimatedButtonWrapper>
                  <Button
                    onClick={() => handleDownloadPDF(report.id)}
                    className="relative bg-orange-500 hover:bg-orange-600 text-white rounded-full z-10 transform hover:scale-105 transition-all duration-300 font-semibold"
                    size="sm"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                </AnimatedButtonWrapper>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {filteredReports.length === 0 && (
        <Card className="p-12 bg-gradient-to-br from-zinc-800/95 to-zinc-900/95 backdrop-blur-xl rounded-3xl border border-orange-500/40 shadow-2xl shadow-orange-500/10 text-center">
          <FileText className="w-16 h-16 text-orange-400/50 mx-auto mb-4" />
          <p className="text-lg font-semibold text-white/70">No reports found</p>
          <p className="text-sm text-white/50 mt-2">Try adjusting your search query</p>
        </Card>
      )}

      {/* PDF Viewer Modal */}
      {viewingReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm">
          <div className="relative w-full h-full max-w-6xl mx-4 my-4 bg-gradient-to-br from-zinc-800/95 to-zinc-900/95 rounded-3xl border border-orange-500/40 shadow-2xl shadow-orange-500/20 flex flex-col">
            {/* Modal Header */}
            <div className="flex items-center justify-between p-6 border-b border-zinc-700/50">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-3xl bg-gradient-to-br from-orange-500/20 to-orange-600/10 flex items-center justify-center border border-orange-500/30 shadow-md">
                  <FileText className="w-6 h-6 text-orange-400" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-orange-400">{viewingReport.patientName}</h2>
                  <p className="text-sm text-white/70">{viewingReport.type} • {formatDate(viewingReport.generatedDate)}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <AnimatedButtonWrapper>
                  <Button
                    onClick={() => handleDownloadPDF(viewingReport.id)}
                    className="relative bg-orange-500 hover:bg-orange-600 text-white rounded-full z-10 transform hover:scale-105 transition-all duration-300 font-semibold"
                    size="sm"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                </AnimatedButtonWrapper>
                <Button
                  onClick={() => setViewingReport(null)}
                  className="rounded-full bg-zinc-800/50 border border-zinc-700/50 text-white hover:bg-zinc-800 hover:border-orange-500/50 transition-all"
                  size="sm"
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>
            </div>

            {/* PDF Viewer Content */}
            <div className="flex-1 overflow-auto p-6">
              <div className="bg-white rounded-2xl p-8 shadow-lg min-h-full">
                <div className="max-w-4xl mx-auto">
                  <div className="mb-8">
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">Patient Medical Report</h1>
                    <p className="text-sm text-gray-600">Generated by AI Chatbot</p>
                    <div className="w-20 h-1 bg-orange-500 rounded-full mt-4"></div>
                  </div>

                  <div className="space-y-6 text-gray-800">
                    <section>
                      <h2 className="text-xl font-bold text-gray-900 mb-4">Patient Information</h2>
                      <div className="bg-gray-50 rounded-xl p-4 space-y-2">
                        <div className="flex justify-between">
                          <span className="font-semibold">Patient Name:</span>
                          <span>{viewingReport.patientName}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="font-semibold">Report Type:</span>
                          <span>{viewingReport.type}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="font-semibold">Generated Date:</span>
                          <span>{formatDate(viewingReport.generatedDate)}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="font-semibold">Status:</span>
                          <Badge className="bg-green-500/10 text-green-700 border-green-500/30">{viewingReport.status}</Badge>
                        </div>
                      </div>
                    </section>

                    <section>
                      <h2 className="text-xl font-bold text-gray-900 mb-4">Report Summary</h2>
                      <div className="bg-orange-50 rounded-xl p-6 border border-orange-200">
                        <p className="text-gray-700 leading-relaxed mb-4">
                          This is a comprehensive medical report generated by our AI-powered chatbot system.
                          The report contains detailed analysis of patient health records, visit history, and medical summaries.
                        </p>
                        <p className="text-gray-700 leading-relaxed mb-4">
                          The AI system has analyzed the patient's medical history, visit patterns, and health data
                          to provide insights and recommendations for continued care.
                        </p>
                      </div>
                    </section>

                    <section>
                      <h2 className="text-xl font-bold text-gray-900 mb-4">Key Findings</h2>
                      <ul className="space-y-2 list-disc list-inside text-gray-700">
                        <li>Patient records have been reviewed and analyzed</li>
                        <li>Medical history has been compiled and verified</li>
                        <li>Recommendations have been generated based on AI analysis</li>
                        <li>Treatment patterns and outcomes have been documented</li>
                      </ul>
                    </section>

                    <section className="pt-6 border-t border-gray-200">
                      <p className="text-xs text-gray-500 text-center">
                        This report was automatically generated by the healthcare AI system and contains sensitive medical information.
                        Please handle with confidentiality.
                      </p>
                      <p className="text-xs text-gray-400 text-center mt-2">
                        Report ID: {viewingReport.id} • Generated: {new Date(viewingReport.generatedDate).toLocaleString()}
                      </p>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
    </PageWrapper>
  )
}
